[versions]
androidgradle = "7.2.0-beta01"
compose = "1.0.1"
compose-jetbrains = "1.1.0-rc01"
constraintlayout = "1.0.0-beta01"
coroutines = "1.6.0-native-mt"
datetime = "0.3.2"
koin = "3.1.5"
kotlin = "1.6.10"
serialization = "1.3.2"
voyager = "1.0.0-beta14"

[libraries]
plugin-android-gradle = { module = "com.android.tools.build:gradle", version.ref = "androidgradle" }
plugin-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-versions-gradle = "com.github.ben-manes:gradle-versions-plugin:0.41.0"

androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"
androidx-core = "androidx.core:core-ktx:1.7.0"

compose-android-activity = "androidx.activity:activity-compose:1.4.0"

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-bottomsheet = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }