[versions]
compileSdk = "32"
minSdk = "21"
targetSdk = "32"

androidgradle = "7.1.2"
compose = "1.0.1"
compose-jetbrains = "1.1.0"
constraintlayout = "1.0.0-beta01"
coroutines = "1.6.0-native-mt"
decompose = "0.5.2"
koin = "3.2.0-beta-1"
kotlin = "1.6.10"
ktor = "1.6.8"
material = "1.5.0"
mvikotlin = "2.0.4"

[libraries]
plugin-android-gradle = { module = "com.android.tools.build:gradle", version.ref = "androidgradle" }
plugin-compose-gradle = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-jetbrains" }
plugin-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-serialization-gradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-versions-gradle = "com.github.ben-manes:gradle-versions-plugin:0.42.0"

android-material = { module = "com.google.android.material:material", version.ref = "material" }

androidx-activity-compose = "androidx.activity:activity-compose:1.4.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"
androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.1"
androidx-window = "androidx.window:window:1.0.0"

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2"

kotlin-csv = "com.github.doyaaaaaken:kotlin-csv-jvm:1.2.0"

ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }

mvikotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }
mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvikotlin" }
mvikotlin-coroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }

themedetector = "com.github.Dansoftowner:jSystemThemeDetector:3.8"